"""empty message

Revision ID: 40471580b50b
Revises: 44e4e9976247
Create Date: 2024-03-10 20:05:14.403924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40471580b50b'
down_revision = '44e4e9976247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('card', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['card'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('card')
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
