"""empty message

Revision ID: 44e4e9976247
Revises: 9b5d01aed99e
Create Date: 2024-03-10 11:27:48.834655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e4e9976247'
down_revision = '9b5d01aed99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cover', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('StockCount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('AvailableCopies', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('BorrowedTimes', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('BorrowedTimes')
        batch_op.drop_column('AvailableCopies')
        batch_op.drop_column('StockCount')
        batch_op.drop_column('Cover')

    # ### end Alembic commands ###
