"""empty message

Revision ID: 9b5d01aed99e
Revises: a11f47cd53f6
Create Date: 2024-03-08 15:17:59.804523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5d01aed99e'
down_revision = 'a11f47cd53f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Synopsis', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('Synopsis')

    # ### end Alembic commands ###
